# Generated by Django 3.2.7 on 2021-09-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210928_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeunlike',
            old_name='Like',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='likeunlike',
            old_name='Unlike',
            new_name='unlike',
        ),
    ]
