# Generated by Django 3.2.7 on 2021-09-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210928_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlikecount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='UserCountryHolidayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_info', models.TextField(blank=True, null=True)),
                ('holidays_info', models.TextField(blank=True, null=True)),
                ('user_uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
