# Generated by Django 3.2.7 on 2021-09-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210928_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercountryholidayinfo',
            name='user_uuid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
